### ISSUE TITLE
docs: atomWithProxy example should convey the bridge between jotai and valtio

### ISSUE THREAD

**Issue by dmaskasky** [jotaijs/jotai-valtio#7]
https://jotai.org/docs/integrations/valtio#atomwithproxy

The example doesn't demonstrate how jotai and valtio are connected. This may be confusing for new developers. I recommend modifying this example to show both jotai and valtio being modified to demonstrate this two-way binding.

**Comment by dai-shi** [comment]
I think I assumed valtio users already know it, but you are right. Please feel free to submit a PR there!
